'use client'

import { useEffect, useRef, useState } from 'react'
import { Activity, Bell, Camera, Check, ChevronRight, Circle, Fan, Home, Lightbulb, Lock, Mic, MoreHorizontal, Power, RefreshCw, Shield, Thermometer, Video, Wifi, X, Zap } from 'lucide-react'

type Device = { id: string; name: string; room: string; value: string; state: 'online' | 'warning' | 'offline'; icon: typeof Fan }

const seedDevices: Device[] = [
  { id: 'climate', name: 'Climate', room: 'Living room', value: '22.4° C', state: 'online', icon: Thermometer },
  { id: 'fan', name: 'Ceiling fan', room: 'Living room', value: 'On · 2.1 kW', state: 'warning', icon: Fan },
  { id: 'light', name: 'Ambient lights', room: 'Living room', value: '64%', state: 'online', icon: Lightbulb },
  { id: 'door', name: 'Front door', room: 'Entryway', value: 'Locked', state: 'online', icon: Lock },
]

function Header({ onPrivacy }: { onPrivacy: () => void }) {
  return <header className="app-header"><div className="brand"><span className="brand-mark">Q</span><span>QSENSE</span><b>LIVE</b></div><div className="header-meta"><span className="pulse"><i /> All systems connected</span><button aria-label="Notifications" className="header-icon"><Bell size={18} /><em>2</em></button><button aria-label="Privacy settings" className="header-icon" onClick={onPrivacy}><Shield size={18} /></button><div className="avatar">JM</div></div></header>
}

function CameraPanel({ active, onStart, onStop }: { active: boolean; onStart: () => void; onStop: () => void }) {
  const videoRef = useRef<HTMLVideoElement>(null)
  const [stream, setStream] = useState<MediaStream | null>(null)
  const [error, setError] = useState('')
  useEffect(() => () => stream?.getTracks().forEach(track => track.stop()), [stream])
  useEffect(() => { if (active && !stream) navigator.mediaDevices?.getUserMedia({ video: true, audio: false }).then(s => { setStream(s); if (videoRef.current) videoRef.current.srcObject = s }).catch(() => setError('Camera permission is needed for live preview.')) }, [active, stream])
  useEffect(() => { if (videoRef.current && stream) videoRef.current.srcObject = stream }, [stream])
  return <section className="panel camera-panel"><div className="panel-heading"><div><span className="eyebrow">LIVE CAMERA</span><h2>Living room</h2></div><span className="live-chip"><i /> {active ? 'LIVE NOW' : 'PAUSED'}</span></div><div className="camera-frame">{active && stream ? <video ref={videoRef} autoPlay playsInline muted /> : <div className="camera-art"><div className="art-window" /><div className="art-sofa" /><div className="art-lamp" /><div className="art-table" /></div>}<div className="camera-overlay"><span>CAM 01 · 1080P</span><span>{active ? '00:14:32' : 'PREVIEW OFF'}</span></div><div className="scan-corners" /></div>{error && <p className="error-note">{error}</p>}<div className="camera-controls"><button className={active ? 'control active' : 'control'} onClick={active ? onStop : onStart}><Video size={16} /> {active ? 'Stop preview' : 'Start live preview'}</button><button className="icon-control" aria-label="Refresh camera"><RefreshCw size={16} /></button><button className="icon-control" aria-label="More camera options"><MoreHorizontal size={18} /></button></div></section>
}

function DeviceCard({ device, onToggle }: { device: Device; onToggle: (id: string) => void }) { const Icon = device.icon; return <button className="device-card" onClick={() => onToggle(device.id)}><div className={`device-icon ${device.state}`}><Icon size={18} /></div><div className="device-copy"><strong>{device.name}</strong><span>{device.room}</span></div><div className="device-reading"><strong>{device.value}</strong><span className={`state-text ${device.state}`}>{device.state === 'online' ? 'Online' : device.state === 'warning' ? 'Needs attention' : 'Offline'}</span></div><ChevronRight size={16} className="chevron" /></button> }

function AlertCard({ onResolve }: { onResolve: () => void }) { return <section className="alert-card"><div className="alert-icon"><Zap size={19} /></div><div className="alert-copy"><span className="eyebrow">ACTION REQUIRED · 2 MIN AGO</span><h3>Ceiling fan is still running</h3><p>QSense noticed the room is empty and energy use is above your usual baseline.</p><div className="alert-actions"><button onClick={onResolve}><Power size={14} /> Turn off fan</button><button className="dismiss" onClick={onResolve}><X size={15} /> Dismiss</button></div></div></section> }

function App() {
  const [cameraActive, setCameraActive] = useState(false)
  const [devices, setDevices] = useState(seedDevices)
  const [resolved, setResolved] = useState(false)
  const [lastUpdate, setLastUpdate] = useState(new Date())
  const [view, setView] = useState<'dashboard' | 'privacy'>('dashboard')
  useEffect(() => { const timer = setInterval(() => { setLastUpdate(new Date()); setDevices(current => current.map(d => d.id === 'climate' ? { ...d, value: `${(22 + Math.random() * 1.2).toFixed(1)}° C` } : d)) }, 2800); return () => clearInterval(timer) }, [])
  const toggleDevice = (id: string) => setDevices(current => current.map(d => d.id === id && d.id === 'fan' ? { ...d, value: d.value.startsWith('On') ? 'Off · 0 kW' : 'On · 2.1 kW', state: d.value.startsWith('On') ? 'online' : 'warning' } : d))
  if (view === 'privacy') return <main className="privacy-view"><button className="back-link" onClick={() => setView('dashboard')}>← Back to dashboard</button><div className="privacy-card"><Shield size={30} /><span className="eyebrow">QSENSE TRUST CENTER</span><h1>Your home,<br /><em>your control.</em></h1><p>Camera previews run locally in your browser and are never recorded by this prototype. Real integrations can be connected when you choose a device platform.</p><div className="privacy-row"><span>Camera access</span><strong>{cameraActive ? 'Active now' : 'Off'}</strong></div><div className="privacy-row"><span>Device telemetry</span><strong>Local demo stream</strong></div><button className="primary-action" onClick={() => setView('dashboard')}>Return to live view</button></div></main>
  return <main className="app-shell"><Header onPrivacy={() => setView('privacy')} /><div className="dashboard"><div className="welcome-row"><div><span className="eyebrow">MONDAY, AUGUST 25 · 20:42</span><h1>Your home, <em>in focus.</em></h1><p>Live awareness across your space. Changes update automatically.</p></div><div className="connection"><Activity size={17} /><span><strong>Live monitoring</strong><small>Updated {lastUpdate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</small></span></div></div><div className="dashboard-grid"><CameraPanel active={cameraActive} onStart={() => setCameraActive(true)} onStop={() => { setCameraActive(false); setDevices(devices) }} /><section className="panel overview-panel"><div className="panel-heading"><div><span className="eyebrow">HOME OVERVIEW</span><h2>Now</h2></div><span className="health-score"><i /> 86 <small>healthy</small></span></div><div className="metric-grid"><div><Thermometer size={17} /><strong>22.4°</strong><span>Indoor temp</span></div><div><Wifi size={17} /><strong>4 / 4</strong><span>Devices online</span></div><div><Power size={17} /><strong>2.1 kW</strong><span>Energy now</span></div><div><Lock size={17} /><strong>Secure</strong><span>Entry points</span></div></div><div className="activity-line"><span>System activity</span><div className="bars">{Array.from({ length: 24 }).map((_, i) => <i key={i} style={{ height: `${22 + ((i * 17) % 58)}%` }} />)}</div><small>Last 24h</small></div></section></div><div className="section-heading"><div><span className="eyebrow">CONNECTED DEVICES</span><h2>Live device dashboard</h2></div><button className="text-action"><span>Manage devices</span> <ChevronRight size={16} /></button></div><div className="device-grid">{devices.map(device => <DeviceCard key={device.id} device={device} onToggle={toggleDevice} />)}</div><div className="section-heading alert-heading"><div><span className="eyebrow">ALERTS & ACTIONS</span><h2>{resolved ? 'You are all clear.' : 'Needs your attention'}</h2></div>{!resolved && <span className="alert-count">1 open alert</span>}</div>{resolved ? <div className="resolved-banner"><Check size={18} /><span>Fan turned off. Your home is back within its normal energy range.</span></div> : <AlertCard onResolve={() => { setResolved(true); toggleDevice('fan') }} />}<div className="assistant-strip"><div className="assistant-icon"><Mic size={18} /></div><div><span className="eyebrow">ASK QSENSE</span><strong>“Is everything okay at home?”</strong></div><button aria-label="Ask QSense"><ChevronRight size={18} /></button></div></div><footer><span>QSENSE / REAL-TIME HOME INTELLIGENCE</span><span>Local monitoring demo · No device platform connected</span></footer></main>
}
export default function Page() { return <App /> }
